### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by Shreeja1699**
Made Small Creative changes which may attract users

### CODE REVIEW

**Comment by a-developer-and-her-mac** [comment]
@bdanzer @ayoisaiah Sorry to say, but to me this looks like spam.

**Comment by Shreeja1699** [comment]
Sry to here that but it's not an spam do check tha read section in the end I have added some words to improve the contract kindly go through it and approved i need this to get approved  
Thank you anyway ☺️

**Comment by a-developer-and-her-mac** [comment]
@Shreeja1699 Sorry if I'm wrong. 🙂

**Comment by AbdullahKady** [comment]
Hey
This seems like an attempt from the PR author to win a t-shirt through [hacktoberfest](https://hacktoberfest.digitalocean.com/).

If you don't mind, follow the [FAQ](https://hacktoberfest.digitalocean.com/faq) way of dealing with spam.

> **As a maintainer, how should I handle spam pull requests?**
> \+ We dislike seeing spam pull requests just as much as you, so please give them an invalid or spam label and close them

**Pull request closed without merging**
